tap "homebrew/cask-fonts"
tap "withgraphite/tap"

brew "ccat"
brew "fish"
brew "gh"
brew "git"
brew "gitleaks"
brew "jq"
brew "mas"
brew "pre-commit"
brew "shellcheck"
brew "shfmt"
brew "streamlink"
brew "withgraphite/tap/graphite"

cask "1password"
cask "arc"
brew "codex-app"
brew "conductor"
cask "google-chrome"
cask "imageoptim"
cask "raycast"
cask "slack"
cask "spotify"
cask "warp"
cask "zed@preview"
cask "zoom"

cask "font-geist"
cask "font-geist-mono"
cask "font-ibm-plex-mono"
cask "font-inter"
cask "font-iosevka"
